# SPDX-FileCopyrightText: 2026 Jeff Lafitte
# SPDX-License-Identifier: MIT

class TrainingReporter:
    def on_training(self) -> None: ...
    def loading_config(self, config_path:str) -> None: ...
    def report_seed(self, seed:int) -> None: ...
    def report_device(self, device_type:str) -> None: ...
    def loading_corpus(self, corpus_path:str) -> None: ...
    def creating_tokenizer(self, tokenizer_type:str) -> None: ...
    def creating_datasets(self, training_weight:int, validation_weight:int, testing_weight:int) -> None: ...
    def creating_model(self, model_type:str) -> None: ...
    def compiling_model(self) -> None: ...
    def creating_optimizer(self, optimizer_type:str) -> None: ...
    def report_config(self, batch_size:int, iteration_limit:int, evaluation_period:int, patience:int) -> None: ...
    def on_start_training(self) -> None: ...
    def on_evaluation(
        self,
        iteration      : int,
        learning_rate  : float,
        training_loss  : float,
        validation_loss: float,
        is_best        : bool) -> None: ...
    def on_lost_patience(self) -> None: ...
    def on_finish_training(self, iteration:int, trained_iteration:int, validation_loss:float) -> None: ...
    def report_testing_loss(self, testing_loss:float) -> None: ...
    def saving_checkpoint(self, checkpoint_path:str) -> None: ...
    def on_done(self) -> None: ...
